// Blogs
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NTJmMDVjMjZjMjI3YWM2NTdiOTE2NzUiLCJpYXQiOjE2OTc1ODA0OTgsImV4cCI6MTY5NzU4NDA5OH0.zPJY3OoCMsfwyqesYk9vZ9-jmaOOahqItfBBYyG4dpU

{
	"title": "Blog to delete",
	"author": "Edsger W. Dijkstra",
	"url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
	"likes": 5
}

###
DELETE http://localhost:3003/api/blogs/652f05f76c227ac657b9167b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NTJmMDVjMjZjMjI3YWM2NTdiOTE2NzUiLCJpYXQiOjE2OTc1ODA0OTgsImV4cCI6MTY5NzU4NDA5OH0.zPJY3OoCMsfwyqesYk9vZ9-jmaOOahqItfBBYyG4dpU


// Users
###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "mluukkai",
	"name": "Matti Luukkainen",
	"password": "salainen"
}


// Login
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
	"username": "mluukkai",
	"password": "salainen"
}
